FROM node:18-slim

# Install dependency sistem untuk hardware monitoring
RUN apt-get update && apt-get install -y lm-sensors iproute2 && rm -rf /var/lib/apt/lists/*

# Install PM2 secara global
RUN npm install pm2 -g

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

# Menggunakan pm2-runtime agar kontainer tidak langsung exit
# Ganti 'index.js' dengan nama file script kamu jika berbeda
CMD ["pm2-runtime", "server.js"]